repos:
      - repo: https://github.com/timothycrosley/isort
        rev: 5.7.0
        hooks:
              - id: isort
      - repo: https://github.com/ambv/black
        rev: 20.8b1
        hooks:
              - id: black
      - repo: https://gitlab.com/pycqa/flake8
        rev: 3.8.4
        hooks:
              - id: flake8
      - repo: local
        hooks:
              - id: clang-format
                name: clang-format
                description: Format files with ClangFormat.
                entry: clang-format -i
                language: system
                files: \.(cu|cuh|h|cc|inl)$
                args: ['-fallback-style=none']
default_language_version:
      python: python3
