name: Build legate.core
on: 
  push:
    branches-ignore:
      - gh-pages  # deployment target branch (this workflow should not exist on that branch anyway)
  pull_request:
    branches-ignore:
      - gh-pages  # deployment target branch (this workflow should not exist on that branch anyway)
env:
  COMMIT: ${{ github.event.pull_request.head.sha || github.sha }}
  PROJECT: github-pandas-ci
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Run CI build
        run: |
          /data/github-runner/legate-bin/setup.sh
          cd legate-ci
          cd github-ci/
          cd legate.pandas
          rm -rf ngc-artifacts
          ./build.sh > ${COMMIT}-build.log 2>&1
          cat *artifacts/*/*
      - name: Upload Build Log
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: build-log
          path: ./**/${{ env.COMMIT }}-build.log.gpg
  test:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Run CPU tests
        run: |
          /data/github-runner/legate-bin/setup.sh
          cd legate-ci
          cd github-ci/
          cd legate.pandas
          if [[ ! -d ngc-artifacts ]]
          then
            mkdir ngc-artifacts
          else
            rm -rf ngc-artifacts/*
          fi
      - name: Test single CPU
        run: ./test.sh --cpus 1 -j 1 > ${COMMIT}-test-cpu.log 2>&1
      - name: Test two CPUs
        if: always()
        run: ./test.sh --cpus 2 -j 1 >> ${COMMIT}-test-cpu.log 2>&1
      - name: Process output
        if: always()
        run: |
          /data/github-runner/legate-bin/encrypt.sh ${COMMIT}-test-cpu.log 2>&1
          cat *artifacts/*/*
      - name: Upload Build Log
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-cpu-log
          path: ./**/${{ env.COMMIT }}-test-cpu.log.gpg
  test-gpu:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Run GPU tests
        run: |
          /data/github-runner/legate-bin/setup.sh
          cd legate-ci
          cd github-ci/
          cd legate.pandas
          if [[ ! -d ngc-artifacts ]]
          then
            mkdir ngc-artifacts
          else
            rm -rf ngc-artifacts/*
          fi
      - name: Test GPU
        run: ./test.sh --use cuda --gpus 1 -j 1 > ${COMMIT}-test-gpu.log 2>&1
      - name: Test two GPUs
        run: ./test.sh --use cuda --gpus 2 -j 1 >> ${COMMIT}-test-gpu.log 2>&1
      - name: Process output
        if: always()
        run: |
          /data/github-runner/legate-bin/encrypt.sh ${COMMIT}-test-gpu.log
          cat *artifacts/*/*
      - name: Upload Build Log
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-gpu-log
          path: ./**/${{ env.COMMIT }}-test-gpu.log.gpg